name: Build

on:
  push:
    branches: [album, main]
  pull_request:
    branches: [album, main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.5
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          . /opt/esp/idf/export.sh
          idf.py set-target esp32s3
          idf.py build
